version: "3.3"
services:
  web:
    container_name: web
    build:
      context: ./webBuild
    volumes:
      - ./app:/var/www
      - ./app/public:/var/www/html
      - ./var/log:/var/log/php
    ports:
      - "8800:80"
    restart: always
